static_view_size: 30
img_shapes: [64, 64, 3] #itan [256, 256, 3] 
height: 16              #otan allazo to megethos tis eikonas prepei na allazo kai to height kai width    
width: 16               #giati ayta einai gia tin mask kai prepei na einai arketa mikroteri tis eikonas
max_delta_height: 32
max_delta_width: 32
batch_size: 32 #itan 16
vertical_margin: 0
horizontal_margin: 0
gan_with_mask: False
